// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAin1wS6Xs8Swio211uvO55AjrPYbIlKsg',
    appId: '1:990319184014:web:a2392bee5157e5fc1361df',
    messagingSenderId: '990319184014',
    projectId: 'kakeibo-c9ec9',
    authDomain: 'kakeibo-c9ec9.firebaseapp.com',
    storageBucket: 'kakeibo-c9ec9.appspot.com',
    measurementId: 'G-8ZW6C3PSXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSBCNw38GnoQf__BU1ZKazvNVrk7z2hAw',
    appId: '1:990319184014:android:71990b46c8651ef61361df',
    messagingSenderId: '990319184014',
    projectId: 'kakeibo-c9ec9',
    storageBucket: 'kakeibo-c9ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLttNif1LQZz1zFx1v1OkpNQnjfnpVNT8',
    appId: '1:990319184014:ios:12075f03cdec2f6d1361df',
    messagingSenderId: '990319184014',
    projectId: 'kakeibo-c9ec9',
    storageBucket: 'kakeibo-c9ec9.appspot.com',
    iosClientId:
        '990319184014-6te76rkkoee4jgvm7sock43lq2hiltac.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakeibo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLttNif1LQZz1zFx1v1OkpNQnjfnpVNT8',
    appId: '1:990319184014:ios:12075f03cdec2f6d1361df',
    messagingSenderId: '990319184014',
    projectId: 'kakeibo-c9ec9',
    storageBucket: 'kakeibo-c9ec9.appspot.com',
    iosClientId:
        '990319184014-6te76rkkoee4jgvm7sock43lq2hiltac.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakeibo',
  );
}
